image: node:11

cache:
  paths:
  - node_modules/

stages:
  - test

test:
  stage: test
  script:
   - npm install
   - npm test
  artifacts:
      paths:
        - coverage/
eslint:
  stage: test
  script:
    - npm install
    - $(npm bin)/eslint .
    